### ISSUE TITLE
Add support to disable bold style

### ISSUE THREAD

**Issue by mengelbrecht** [NovaDev94/lightline-onedark#1]
In my current setup the only bold style usage is in the `onedark` lightline theme. It would be nice if it can be disabled to match the rest of the vim appearance.

**Comment by novadev94** [comment]
Hi @mgee. Thanks for your suggestions. I've added an option `lightline#onedark#disable_bold_style` here https://github.com/NovaDev94/lightline-onedark/commit/cc2e83e5c7b38e25a915f8273e1a36bdce56e271.  

You can use it by  

``` viml
let g:lightline#onedark#disable_bold_style = 1
```

README is also updated with configuration information and example. Hope it will be useful to you :)

**Comment by mengelbrecht** [comment]
Thanks, it works great! :-)
